export const countdownQuotes = [
  'Step by step. One problem at a time.',
  'No calculator needed. Trust your head.',
  'The mind is a muscle. This is your rep for today.',
  "Singapore's 12-year-olds don't panic. Neither will you.",
  'Slow down to speed up. Read every word.',
  "You've solved harder things in life than this.",
  'Think before you type. Accuracy, then speed.',
  'Resist the calculator. Your brain is enough.',
  'One question. Full focus. Nothing else matters right now.',
  'The fundamentals are never wrong. Trust them.',
  'Primary school logic. Adult patience. Let\'s go.',
  'You learned this once. It\'s still in there.',
  'No shortcuts today. Just clean thinking.',
  'The answer is simpler than you think. Probably.',
  'Your streak is on the line. No pressure, though.',
  'Twelve-year-olds do this before recess. Just saying.',
  'A clear mind finds the answer. Breathe first.',
  'Precision matters. Careless mistakes are the only enemy.',
  'Read the question twice. Then answer once.',
  'Back to basics. This is where clarity lives.',
  'There is always exactly one right answer. Find it.',
  'If in doubt, go back to first principles.',
  'One minute of full focus. That\'s all it takes.',
  'This question was designed for a child. Rise to the occasion.',
  'Quiet the noise. Let the math speak.',
  'You don\'t need luck. You need logic.',
  'The answer exists. Your job is simply to find it.',
  'Draw it out if you have to. Whatever works.',
  "Today's PSLE question. Tomorrow's party trick.",
  'Mental clarity, built one problem at a time.',
  'Your mind is your sharpest tool. Use it.',
  'PSLE standard. Your standard. Let\'s find out.',
  "Don't rush. Don't freeze. Just think.",
  'Some problems in life are actually this clean.',
  'The strongest minds stay sharp daily. Like you.',
  'Focus. Read. Think. Answer. In that order.',
  'You handle tougher things before breakfast. This is nothing.',
  'Real problems. Real thinking. Real satisfaction when you get it.',
  'The numbers are patient. Take your time.',
  'Somewhere a child aced this without a second thought. Beat them.',
  'Every morning sharpens the blade. This is yours.',
  'Your brain warmed up for this. Ready when you are.',
  'A little discomfort means the muscle is working.',
  'There are no tricks here — only the math.',
  'This is your daily minute of pure thought. Make it count.',
  'Commit to the read. Commit to the answer.',
  'Mental sharpness is a daily practice. Here\'s yours.',
  'The fundamentals outlast every shortcut. Back to them.',
  "The question doesn't care how long it's been. Neither should you.",
  'One right answer. One attempt. One shot. Go.',
]

export const suspensePhrases = [
  'Marking your answer...',
  'Cross-referencing the answer key...',
  'The examiner is deliberating...',
  'Red pen or green — about to find out...',
  'Running the numbers...',
  'The verdict is being calculated...',
  "You either got it or you didn't. Almost time to know.",
  "Somewhere, a 12-year-old already knew the answer.",
  "Whatever you wrote, it's too late to change it now.",
  "The math doesn't care about your feelings...",
  'One correct answer exists in the universe. Did you find it?',
  'A correct answer was submitted today. Was it yours?',
  'Consulting the answer key...',
  "Schrödinger's answer — right and wrong until revealed.",
  'The leaderboard is paying attention...',
  'Your answer has been noted. Judging in progress.',
  "We're just being dramatic. The calculation is already done.",
  'Checking your working...',
  "Hold your breath. Or don't. The result won't change.",
  'This is the part that separates the contenders...',
  "The numbers have spoken. We're translating.",
  'Confidence level: calculating...',
  'Silence before the verdict...',
  "It's written. It's sealed. Almost revealed.",
  'The teacher has the paper. Pen is poised.',
  'Awaiting the inevitable...',
  "Your fate is already determined. We're just showing you.",
  'Every millisecond counts. Especially the ones before this moment.',
  'The algorithm is unimpressed by nerves. Checking now.',
  'This is mathematically the most suspenseful moment of your day.',
  "The answer key doesn't negotiate.",
  'Tabulating your score...',
  'Marking in red or green. Moment of truth incoming.',
  'Trust your working. Or start worrying. One of those applies.',
  "You can't unsend this answer. Moment arriving.",
  'The correct answer is a fixed point in the universe. Checking if you found it.',
  'Checking if your answer survived contact with reality...',
  'Your brain did its best. Mathematics will now respond.',
  'Deep in a server somewhere, your answer is being judged.',
  'Examiner mode: activated.',
  'The numbers are conferring...',
  'This moment before knowing — pure exam anxiety, distilled.',
  "You wrote an answer. The mark scheme has opinions about it.",
  'Relax. Tense up. One of those reactions is about to be correct.',
  'Your answer: submitted. Fate: pending.',
  'Singapore standard marking in progress...',
  'The answer exists. The question is whether yours matches it.',
  "Comparing answers across today's challengers...",
  "Almost ready to reveal what the universe decided...",
  "The result is sealed. The reveal is imminent.",
]
